create profile page
GenericSoft/GDR-Generic-Desk-Reservation pull request #24
Opened 2023-05-30 10:35 UTC by NadyaPeycheva

2023-06-08 09:27 UTC, kalinadukova commented on src/components/ProfileContent/ProfileContent.tsx
> +        setErrorMsg('Pleas enter your job role');
there is a typo, on line 83 and 87 too

2023-06-08 09:34 UTC, mariyaniliev commented on src/components/ProfileContent/ProfileContent.tsx
> +  const isDisabledButton = userProps.readOnlyValue;
Need to be 'isButtonDisabled'

2023-06-08 09:34 UTC, mariyaniliev commented on src/components/ProfileContent/ProfileContent.tsx
> +      }
Use the service for the validation. ( Utils/validations)
For the first and last name, add validation only for the field not to be empty.

2023-06-08 09:34 UTC, mariyaniliev commented on src/pages/Profile/Profile.tsx
> +          userId={user.userId}
Add this data to Redux store and do not pass them like props

2023-06-08 09:34 UTC, mariyaniliev commented on src/pages/Profile/Profile.tsx
> +          readOnlyValue={readOnlyValue}
This name does not say anything

2023-06-08 09:34 UTC, mariyaniliev commented on src/pages/Profile/Profile.tsx
> +  };
Combine these two into one Function, and instead of adding true or false, just toggle between states (check on the internet how to see the old state)

2023-06-08 09:34 UTC, mariyaniliev commented on src/pages/Profile/Profile.tsx
> +          email={user.email}
Add this data to Redux store and do not pass them like props

2023-06-08 09:34 UTC, mariyaniliev commented on src/components/App/App.tsx
> +    <div className={`App`}>
Why does the class name have these extra brackets

2023-06-08 09:34 UTC, mariyaniliev commented on src/components/InputField/InputField.scss
> +}
Add a parent node

2023-06-08 09:34 UTC, mariyaniliev commented on src/components/ProfileCard/ProfileCard.scss
> +}
Need to have a parent Node

2023-06-08 09:34 UTC, mariyaniliev commented on src/components/ProfileCard/ProfileCard.tsx
> +};
Add empty row at the top and at the bottom

2023-06-08 09:34 UTC, mariyaniliev commented on src/components/ProfileContent/ProfileContent.scss
> +}
Parent Node!

2023-06-08 09:34 UTC, mariyaniliev commented on src/components/ProfileContent/ProfileContent.tsx
> +const ProfileContent = (userProps: UserPropsType) => {
Get the userProps date from the store; if you do not have it there, put it

2023-06-08 09:34 UTC, mariyaniliev commented on src/pages/Profile/Profile.tsx
> +const Profile = () => {
Add Space here, separate the imports from the main function

2023-06-09 13:46 UTC, kalinadukova requested changes

2023-06-09 13:46 UTC, kalinadukova commented on src/components/ProfileCard/ProfileCard.tsx
> +const ProfileCard = (props: PropsType) => {
use our props type naming convention 
for example ProfileCardProps

2023-06-09 13:46 UTC, kalinadukova commented on src/components/ProfileContent/ProfileContent.tsx
> +const ProfileContent = (props: PropsType) => {
use our props type naming convention

2023-06-09 13:46 UTC, kalinadukova commented on src/components/ProfileContent/ProfileContent.tsx
> +      occupationRef.current.value = user.jobRole || '';
what is occupationRef?

2023-06-09 13:46 UTC, kalinadukova commented on src/components/ProfileContent/ProfileContent.tsx
>        countyRef.current.value = '';
what is county?

2023-06-09 13:46 UTC, kalinadukova commented on src/components/ProfileContent/ProfileContent.tsx
> +            <button
use our Bootstrap buttons for cancel and save

2023-06-09 13:46 UTC, kalinadukova commented on src/components/DropDown/DropDown.tsx
> +      <NavDropdown.Item href="/profile">
href refreshes the page
use onClick function with useNavigate() hook

2023-06-09 13:46 UTC, kalinadukova commented on src/components/ProfileCard/ProfileCard.tsx
> +          <Card.Link href="/dashboard">
href refreshed the app
use onClick with useNavigate() hook

2023-06-09 13:46 UTC, kalinadukova commented on src/components/UserImage/UserImage.tsx
>  const UserImage = (userData: UserData) => {
rename userData to props 
this is a convention

2023-06-09 13:46 UTC, kalinadukova commented on src/components/DropDown/DropDown.tsx
>  const DropDown = (user: User) => {
rename user to props
this is a convention

2023-06-09 13:46 UTC, kalinadukova commented on src/interfaces/User.ts
> +export interface ReturnedFieldsType {
what is this and where is it used?

2023-06-12 14:51 UTC, ZarinaValeva requested changes

2023-06-12 14:51 UTC, ZarinaValeva commented on src/components/ProfileContent/ProfileContent.scss
> +    &__buttons {
Use our already created classes for buttons.

2023-06-12 14:51 UTC, ZarinaValeva commented on src/components/ProfileContent/ProfileContent.tsx
> +            <Col>First Name</Col>
If you want, you can add * to the required fields, which are First and Last name, but Country, Birthday and Job role shouldn't be required, hence the user should be able to change and save only 1 of the fields. Also there isn't a validation for ' ' and I can change my names to just string with a space. 
![image](https://github.com/GenericSoft/GDR-Generic-Desk-Reservation/assets/31138395/30812cc8-3f65-432a-862c-d5069cd0c17b)

2023-06-12 14:51 UTC, ZarinaValeva commented on src/pages/Profile/Profile.tsx
> +  return (
Missing navigation and footer.

2023-06-14 06:19 UTC, kalinadukova requested changes

2023-06-14 06:19 UTC, kalinadukova commented on src/utils/validations.ts
> +};
why is the type declaration here, please move it into interfaces or at the top of the page
please leave an empty row between the functions to improve code readability

2023-06-14 06:19 UTC, kalinadukova commented on src/components/UserImage/UserImage.tsx
> +type PropsType = { userImage: string; firstName: string; lastName: string };
why is the type declaration between imports? 
rename PropsType

2023-06-14 06:27 UTC, kalinadukova requested changes

2023-06-14 06:27 UTC, kalinadukova commented on src/components/DropDown/DropDown.tsx
> +const DropDown = (userProps: UserPropsType) => {
rename

2023-06-14 09:52 UTC, ZarinaValeva requested changes

2023-06-14 09:52 UTC, ZarinaValeva commented on src/components/ProfileContent/ProfileContent.tsx
> +              onClick={updateProfileFieldsDb}
On click Save we should show a loader for user to know that something is happening and hide the functionality to change the fields.

2023-06-14 09:52 UTC, ZarinaValeva commented on src/components/ProfileContent/ProfileContent.tsx
> +                className="profile-form"
Clear the placeholder when user is deleting the current value from the input, because it looks like deletion is not happening.

2023-06-14 13:07 UTC, ZarinaValeva approved these changes

2023-06-14 13:18 UTC, kalinadukova approved these changes

2023-06-14 13:39 UTC, merged